#include "export/WorkflowExporter.hpp"

#include <QJsonArray>
#include <QJsonObject>
#include <QTemporaryFile>
#include <QTest>

class WorkflowExporterTests : public QObject
{
    Q_OBJECT

private:
    QJsonObject makeWorkflow(QJsonArray const &nodes, QJsonArray const &connections = {})
    {
        QJsonObject wf;
        wf["version"] = 2;
        wf["nodes"] = nodes;
        wf["connections"] = connections;
        return wf;
    }

    QJsonObject makeNode(int id, QString const &type, QString const &displayName,
                          QJsonObject const &properties = {})
    {
        QJsonObject node;
        node["id"] = id;
        node["type"] = type;
        node["displayName"] = displayName;
        node["properties"] = properties;
        QJsonObject pos;
        pos["x"] = 0.0;
        pos["y"] = 0.0;
        node["position"] = pos;
        return node;
    }

    QJsonObject makeConnection(int outId, int outPort, int inId, int inPort)
    {
        QJsonObject conn;
        conn["outNodeId"] = outId;
        conn["outPortIndex"] = outPort;
        conn["inNodeId"] = inId;
        conn["inPortIndex"] = inPort;
        return conn;
    }

private slots:
    void emptyWorkflowFails()
    {
        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow({}), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(!result.success);
        QVERIFY(!result.errorMessage.isEmpty());
    }

    void langchainExportContainsImports()
    {
        QJsonObject promptProps;
        promptProps["systemPrompt"] = "You are helpful.";
        promptProps["userPromptTemplate"] = "Summarize: {input}";

        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));
        nodes.append(makeNode(1, "prompt", "My Prompt", promptProps));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from langchain_core.prompts import ChatPromptTemplate"));
        QVERIFY(result.code.contains("Auto-generated by AI Workflow Editor"));
    }

    void langchainExportGeneratesPromptNode()
    {
        QJsonObject props;
        props["systemPrompt"] = "Be concise.";
        props["userPromptTemplate"] = "{input}";

        QJsonArray nodes;
        nodes.append(makeNode(1, "prompt", "My Prompt", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("my_prompt = ChatPromptTemplate.from_messages"));
        QVERIFY(result.code.contains("Be concise."));
    }

    void langchainExportGeneratesLlmNode()
    {
        QJsonObject props;
        props["modelName"] = "gpt-4o";
        props["temperature"] = 0.7;
        props["maxTokens"] = 2048;

        QJsonArray nodes;
        nodes.append(makeNode(1, "llm", "My LLM", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from langchain_openai import ChatOpenAI"));
        QVERIFY(result.code.contains("my_llm = ChatOpenAI("));
        QVERIFY(result.code.contains("model=\"gpt-4o\""));
        QVERIFY(result.code.contains("temperature=0.7"));
        QVERIFY(result.code.contains("max_tokens=2048"));
    }

    void langchainExportGeneratesChainAssembly()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        QJsonObject promptProps;
        promptProps["userPromptTemplate"] = "{input}";
        nodes.append(makeNode(1, "prompt", "Prompt", promptProps));

        QJsonObject llmProps;
        llmProps["modelName"] = "gpt-4";
        nodes.append(makeNode(2, "llm", "LLM", llmProps));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));
        connections.append(makeConnection(1, 0, 2, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("prompt_chain = prompt | llm"));
    }

    void langchainExportGeneratesHttpRequestNode()
    {
        QJsonObject props;
        props["method"] = "POST";
        props["url"] = "https://api.example.com/data";
        props["timeoutMs"] = 5000;

        QJsonArray nodes;
        nodes.append(makeNode(1, "httpRequest", "API Call", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("import requests"));
        QVERIFY(result.code.contains("requests.post("));
        QVERIFY(result.code.contains("https://api.example.com/data"));
    }

    void langchainExportGeneratesToolNode()
    {
        QJsonObject props;
        props["toolName"] = "web_search";

        QJsonArray nodes;
        nodes.append(makeNode(1, "tool", "Search Tool", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from langchain_core.tools import tool"));
        QVERIFY(result.code.contains("@tool"));
        QVERIFY(result.code.contains("web_search"));
    }

    void langchainExportGeneratesAgentNode()
    {
        QJsonObject props;
        props["agentInstructions"] = "Triage the request.";
        props["modelName"] = "gpt-4o";
        props["maxIterations"] = 10;

        QJsonArray nodes;
        nodes.append(makeNode(1, "agent", "My Agent", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("AgentExecutor"));
        QVERIFY(result.code.contains("max_iterations=10"));
    }

    void langchainExportGeneratesMemoryNode()
    {
        QJsonObject props;
        props["memoryKey"] = "chat_history";

        QJsonArray nodes;
        nodes.append(makeNode(1, "memory", "Memory", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("ConversationBufferMemory"));
        QVERIFY(result.code.contains("chat_history"));
    }

    void langchainExportGeneratesConditionNode()
    {
        QJsonArray nodes;
        nodes.append(makeNode(1, "condition", "Check Input", {}));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("def check_input(data):"));
        QVERIFY(result.code.contains("return True"));
    }

    void langchainExportGeneratesOutputNode()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));
        nodes.append(makeNode(1, "output", "Result"));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("result = start"));
    }

    void pythonScriptExportSucceeds()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        QJsonObject promptProps;
        promptProps["userPromptTemplate"] = "{input}";
        nodes.append(makeNode(1, "prompt", "Prompt", promptProps));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonScript);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("#!/usr/bin/env python3"));
        QVERIFY(result.code.contains("def run_workflow():"));
        QVERIFY(result.code.contains("if __name__ == \"__main__\":"));
    }

    void pythonScriptExportGeneratesPipeline()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        QJsonObject llmProps;
        llmProps["modelName"] = "gpt-4";
        nodes.append(makeNode(1, "llm", "LLM", llmProps));
        nodes.append(makeNode(2, "output", "Output"));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));
        connections.append(makeConnection(1, 0, 2, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonScript);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("data = start()"));
        QVERIFY(result.code.contains("data = llm(data)"));
        QVERIFY(result.code.contains("data = output(data)"));
    }

    void topologicalSortRespectsConnections()
    {
        QJsonArray nodes;

        QJsonObject llmProps;
        llmProps["modelName"] = "gpt-4";
        nodes.append(makeNode(2, "llm", "LLM", llmProps));
        nodes.append(makeNode(0, "start", "Start"));

        QJsonObject promptProps;
        promptProps["userPromptTemplate"] = "{input}";
        nodes.append(makeNode(1, "prompt", "Prompt", promptProps));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));
        connections.append(makeConnection(1, 0, 2, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonScript);
        QVERIFY(result.success);
        int startPos = result.code.indexOf("def start()");
        int promptPos = result.code.indexOf("def prompt(");
        int llmPos = result.code.indexOf("def llm(");
        QVERIFY(startPos < promptPos);
        QVERIFY(promptPos < llmPos);
    }

    void variableNameSanitization()
    {
        QJsonArray nodes;
        nodes.append(makeNode(1, "prompt", "My Cool Prompt!!", {}));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("my_cool_prompt = ChatPromptTemplate"));
    }

    void duplicateDisplayNamesGetUniqueSuffix()
    {
        QJsonArray nodes;
        nodes.append(makeNode(1, "prompt", "Prompt", {}));
        nodes.append(makeNode(2, "prompt", "Prompt", {}));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("prompt ="));
        QVERIFY(result.code.contains("prompt_1 ="));
    }

    void exportToFileWritesCorrectly()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        QTemporaryFile tmpFile;
        tmpFile.setAutoRemove(true);
        QVERIFY(tmpFile.open());
        const QString path = tmpFile.fileName();
        tmpFile.close();

        bool ok = WorkflowExporter::exportToFile(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain, path);
        QVERIFY(ok);

        QFile readBack(path);
        QVERIFY(readBack.open(QIODevice::ReadOnly));
        const QString content = QString::fromUtf8(readBack.readAll());
        QVERIFY(content.contains("Auto-generated by AI Workflow Editor"));
        QVERIFY(content.contains("start"));
    }

    void formatDisplayNameReturnsCorrectStrings()
    {
        QCOMPARE(WorkflowExporter::formatDisplayName(WorkflowExporter::Format::PythonLangChain),
                 QStringLiteral("Python (LangChain)"));
        QCOMPARE(WorkflowExporter::formatDisplayName(WorkflowExporter::Format::PythonScript),
                 QStringLiteral("Python Script"));
    }

    void formatFileFilterReturnsPythonFilter()
    {
        QVERIFY(WorkflowExporter::formatFileFilter(WorkflowExporter::Format::PythonLangChain)
                    .contains("*.py"));
        QVERIFY(WorkflowExporter::formatFileFilter(WorkflowExporter::Format::PythonScript)
                    .contains("*.py"));
    }

    void langchainExportGeneratesChatOutputNode()
    {
        QJsonObject props;
        props["messageRole"] = "assistant";
        props["messageTemplate"] = "{{result}}";

        QJsonArray nodes;
        nodes.append(makeNode(1, "chatOutput", "Chat Output", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("def chat_output(content):"));
        QVERIFY(result.code.contains("\"assistant\""));
    }

    void langchainExportGeneratesJsonTransformNode()
    {
        QJsonObject props;
        props["transformJson"] = "{\"key\": \"value\"}";

        QJsonArray nodes;
        nodes.append(makeNode(1, "jsonTransform", "Transform", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("def transform(data):"));
    }

    void langchainExportGeneratesTemplateVariablesNode()
    {
        QJsonObject props;
        props["variablesJson"] = "{\"topic\": \"AI\"}";

        QJsonArray nodes;
        nodes.append(makeNode(1, "templateVariables", "Vars", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("vars = {\"topic\": \"AI\"}"));
    }

    void langchainExportGeneratesRetrieverNode()
    {
        QJsonObject props;
        props["retrieverKey"] = "knowledge_base";

        QJsonArray nodes;
        nodes.append(makeNode(1, "retriever", "KB Retriever", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("knowledge_base"));
        QVERIFY(result.code.contains("TODO: initialize retriever"));
    }

    void fullWorkflowExportEndToEnd()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        QJsonObject promptProps;
        promptProps["systemPrompt"] = "You are a summarizer.";
        promptProps["userPromptTemplate"] = "Summarize: {input}";
        nodes.append(makeNode(1, "prompt", "Summarize Prompt", promptProps));

        QJsonObject llmProps;
        llmProps["modelName"] = "gpt-4o";
        llmProps["temperature"] = 0.3;
        llmProps["maxTokens"] = 512;
        nodes.append(makeNode(2, "llm", "GPT4o", llmProps));

        nodes.append(makeNode(3, "output", "Result"));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));
        connections.append(makeConnection(1, 0, 2, 0));
        connections.append(makeConnection(2, 0, 3, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonLangChain);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("ChatPromptTemplate"));
        QVERIFY(result.code.contains("ChatOpenAI"));
        QVERIFY(result.code.contains("summarize_prompt_chain = summarize_prompt | gpt4o"));
        QVERIFY(result.code.contains("result = gpt4o"));
        QVERIFY(result.code.contains("if __name__"));
    }

    // --- LangGraph tests ---

    void langgraphExportEmptyWorkflowFails()
    {
        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow({}), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(!result.success);
    }

    void langgraphExportContainsStateGraph()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from langgraph.graph import StateGraph, START, END"));
        QVERIFY(result.code.contains("WorkflowState"));
        QVERIFY(result.code.contains("workflow = StateGraph(WorkflowState)"));
    }

    void langgraphExportAddsNodesAndEdges()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));

        QJsonObject promptProps;
        promptProps["userPromptTemplate"] = "{input}";
        nodes.append(makeNode(1, "prompt", "Prompt", promptProps));

        QJsonObject llmProps;
        llmProps["modelName"] = "gpt-4";
        nodes.append(makeNode(2, "llm", "LLM", llmProps));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));
        connections.append(makeConnection(1, 0, 2, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("workflow.add_node(\"start\", start)"));
        QVERIFY(result.code.contains("workflow.add_node(\"prompt\", prompt)"));
        QVERIFY(result.code.contains("workflow.add_node(\"llm\", llm)"));
        QVERIFY(result.code.contains("workflow.add_edge(\"start\", \"prompt\")"));
        QVERIFY(result.code.contains("workflow.add_edge(\"prompt\", \"llm\")"));
        QVERIFY(result.code.contains("workflow.add_edge(START, \"start\")"));
    }

    void langgraphExportCompilesAndRuns()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));
        nodes.append(makeNode(1, "output", "Output"));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("app = workflow.compile()"));
        QVERIFY(result.code.contains("if __name__"));
        QVERIFY(result.code.contains("app.invoke("));
    }

    void langgraphExportHandlesCondition()
    {
        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));
        nodes.append(makeNode(1, "condition", "Check", {}));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("def check(state: WorkflowState) -> str:"));
    }

    void langgraphExportHandlesHttpRequest()
    {
        QJsonObject props;
        props["method"] = "POST";
        props["url"] = "https://api.example.com";
        props["timeoutMs"] = 5000;

        QJsonArray nodes;
        nodes.append(makeNode(1, "httpRequest", "API Call", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("import requests"));
        QVERIFY(result.code.contains("requests.post("));
        QVERIFY(result.code.contains("https://api.example.com"));
    }

    void langgraphExportHandlesTool()
    {
        QJsonObject props;
        props["toolName"] = "web_search";

        QJsonArray nodes;
        nodes.append(makeNode(1, "tool", "Search Tool", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonLangGraph);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from langchain_core.tools import tool"));
        QVERIFY(result.code.contains("@tool"));
        QVERIFY(result.code.contains("web_search"));
    }

    // --- CrewAI tests ---

    void crewaiExportEmptyWorkflowFails()
    {
        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow({}), WorkflowExporter::Format::PythonCrewAI);
        QVERIFY(!result.success);
    }

    void crewaiExportContainsCrewImports()
    {
        QJsonObject agentProps;
        agentProps["agentInstructions"] = "Help the user.";
        agentProps["modelName"] = "gpt-4";

        QJsonArray nodes;
        nodes.append(makeNode(1, "agent", "Helper", agentProps));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonCrewAI);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from crewai import Agent, Task, Crew, Process"));
        QVERIFY(result.code.contains("Auto-generated by AI Workflow Editor"));
    }

    void crewaiExportGeneratesAgentAndCrew()
    {
        QJsonObject agentProps;
        agentProps["agentInstructions"] = "Research topics.";
        agentProps["modelName"] = "gpt-4o";

        QJsonArray nodes;
        nodes.append(makeNode(1, "agent", "Researcher", agentProps));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonCrewAI);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("researcher = Agent("));
        QVERIFY(result.code.contains("role=\"Researcher\""));
        QVERIFY(result.code.contains("gpt-4o"));
        QVERIFY(result.code.contains("crew = Crew("));
        QVERIFY(result.code.contains("agents=[researcher]"));
        QVERIFY(result.code.contains("crew.kickoff()"));
    }

    void crewaiExportGeneratesTaskFromPrompt()
    {
        QJsonObject agentProps;
        agentProps["agentInstructions"] = "Write.";
        agentProps["modelName"] = "gpt-4";

        QJsonObject promptProps;
        promptProps["userPromptTemplate"] = "Summarize the topic.";

        QJsonArray nodes;
        nodes.append(makeNode(0, "start", "Start"));
        nodes.append(makeNode(1, "agent", "Writer", agentProps));
        nodes.append(makeNode(2, "prompt", "Task Prompt", promptProps));

        QJsonArray connections;
        connections.append(makeConnection(0, 0, 1, 0));
        connections.append(makeConnection(1, 0, 2, 0));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes, connections), WorkflowExporter::Format::PythonCrewAI);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("task_prompt_task = Task("));
        QVERIFY(result.code.contains("Summarize the topic."));
        QVERIFY(result.code.contains("tasks=[task_prompt_task]"));
    }

    void crewaiExportGeneratesToolClass()
    {
        QJsonObject props;
        props["toolName"] = "calculator";

        QJsonArray nodes;
        nodes.append(makeNode(1, "tool", "Calc Tool", props));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonCrewAI);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("from crewai.tools import BaseTool"));
        QVERIFY(result.code.contains("class Calc_toolTool(BaseTool):"));
        QVERIFY(result.code.contains("calculator"));
    }

    void crewaiExportMapsLlmToAgent()
    {
        QJsonObject llmProps;
        llmProps["modelName"] = "claude-3.5-sonnet";

        QJsonArray nodes;
        nodes.append(makeNode(1, "llm", "Claude", llmProps));

        auto result = WorkflowExporter::exportWorkflow(
            makeWorkflow(nodes), WorkflowExporter::Format::PythonCrewAI);
        QVERIFY(result.success);
        QVERIFY(result.code.contains("claude = Agent("));
        QVERIFY(result.code.contains("claude-3.5-sonnet"));
    }

    void formatDisplayNameReturnsNewFormats()
    {
        QCOMPARE(WorkflowExporter::formatDisplayName(WorkflowExporter::Format::PythonLangGraph),
                 QStringLiteral("Python (LangGraph)"));
        QCOMPARE(WorkflowExporter::formatDisplayName(WorkflowExporter::Format::PythonCrewAI),
                 QStringLiteral("Python (CrewAI)"));
    }
};

QTEST_MAIN(WorkflowExporterTests)

#include "WorkflowExporterTests.moc"
