#include "inspector/InspectorFieldSchema.hpp"

std::vector<InspectorFieldSchema> builtInInspectorFieldSchemas()
{
    return {
        {QStringLiteral("prompt"),
         QStringLiteral("systemPrompt"),
         QStringLiteral("inspectorPromptSystemLabel"),
         QStringLiteral("inspectorPromptSystemEdit"),
         QStringLiteral("System Prompt"),
         QVariant(),
         QStringLiteral("Optional: define system behavior and constraints."),
         QStringLiteral("Optional. Adds a system-level instruction before the user prompt template runs.")},
        {QStringLiteral("prompt"),
         QStringLiteral("userPromptTemplate"),
         QStringLiteral("inspectorPromptUserTemplateLabel"),
         QStringLiteral("inspectorPromptUserTemplateEdit"),
         QStringLiteral("User Prompt Template"),
         QVariant(),
         QStringLiteral("Example: Summarize the following content: {{input}}"),
         QStringLiteral("Required. Supports workflow variables such as {{input}}.")},
        {QStringLiteral("llm"),
         QStringLiteral("modelName"),
         QStringLiteral("inspectorLlmModelNameLabel"),
         QStringLiteral("inspectorLlmModelNameEdit"),
         QStringLiteral("Model Name"),
         QVariant(),
         QStringLiteral("Enter model identifier"),
         QStringLiteral("Required. Use the model identifier configured by your runtime/backend.")},
        {QStringLiteral("llm"),
         QStringLiteral("temperature"),
         QStringLiteral("inspectorLlmTemperatureLabel"),
         QStringLiteral("inspectorLlmTemperatureSpin"),
         QStringLiteral("Temperature"),
         0.0,
         QString(),
         QStringLiteral("Lower temperatures are more deterministic; higher temperatures are more creative.")},
        {QStringLiteral("llm"),
         QStringLiteral("maxTokens"),
         QStringLiteral("inspectorLlmMaxTokensLabel"),
         QStringLiteral("inspectorLlmMaxTokensSpin"),
         QStringLiteral("Max Tokens"),
         1,
         QString(),
         QStringLiteral("Maximum number of tokens this node may generate.")},
        {QStringLiteral("tool"),
         QStringLiteral("toolName"),
         QStringLiteral("inspectorToolNameLabel"),
         QStringLiteral("inspectorToolNameEdit"),
         QStringLiteral("Tool Name"),
         QVariant(),
         QStringLiteral("Example: web_search"),
         QStringLiteral("Required. Must match a registered tool identifier.")},
        {QStringLiteral("tool"),
         QStringLiteral("timeoutMs"),
         QStringLiteral("inspectorToolTimeoutLabel"),
         QStringLiteral("inspectorToolTimeoutSpin"),
         QStringLiteral("Timeout (ms)"),
         QVariant(),
         QString(),
         QStringLiteral("Optional timeout in milliseconds. Use 0 to keep the runtime default.")},
        {QStringLiteral("tool"),
         QStringLiteral("inputMapping"),
         QStringLiteral("inspectorToolInputMappingLabel"),
         QStringLiteral("inspectorToolInputMappingEdit"),
         QStringLiteral("Input Mapping"),
         QVariant(),
         QStringLiteral("Example: {\"query\": \"{{input}}\"}"),
         QStringLiteral("Optional. Provide a JSON object that maps workflow values into tool inputs.")},
    };
}

std::vector<InspectorSectionSchema> builtInInspectorSectionSchemas()
{
    return {
        {QStringLiteral("prompt"),
         QStringLiteral("inspectorPromptSection"),
         QStringLiteral("Prompt"),
         QStringLiteral("Prompt Settings"),
         QStringLiteral("Edit the prompt template and runtime text for this node."),
         false,
         QString()},
        {QStringLiteral("llm"),
         QStringLiteral("inspectorLlmSection"),
         QStringLiteral("LLM"),
         QStringLiteral("Model Settings"),
         QStringLiteral("Configure the model and generation parameters for this node."),
         false,
         QString()},
        {QStringLiteral("tool"),
         QStringLiteral("inspectorToolSection"),
         QStringLiteral("Tool"),
         QStringLiteral("Tool Settings"),
         QStringLiteral("Configure the tool call, timeout, and input mapping."),
         false,
         QString()},
        {QStringLiteral("start"),
         QStringLiteral(),
         QStringLiteral("Start"),
         QStringLiteral("General Settings"),
         QStringLiteral("This is the workflow entry point."),
         true,
         QStringLiteral("This node has no advanced settings.")},
        {QStringLiteral("condition"),
         QStringLiteral(),
         QStringLiteral("Condition"),
         QStringLiteral("General Settings"),
         QStringLiteral("This node controls workflow branching."),
         true,
         QStringLiteral("This node has no advanced settings.")},
        {QStringLiteral("output"),
         QStringLiteral(),
         QStringLiteral("Output"),
         QStringLiteral("General Settings"),
         QStringLiteral("This node represents the workflow result."),
         true,
         QStringLiteral("This node has no advanced settings.")},
    };
}
