#include "inspector/InspectorFieldSchema.hpp"

std::vector<InspectorFieldSchema> builtInInspectorFieldSchemas()
{
    return {
        {QStringLiteral("prompt"),
         QStringLiteral("systemPrompt"),
         QStringLiteral("System Prompt"),
         QVariant(),
         QStringLiteral("Optional: define system behavior and constraints."),
         QStringLiteral("Optional. Adds a system-level instruction before the user prompt template runs.")},
        {QStringLiteral("prompt"),
         QStringLiteral("userPromptTemplate"),
         QStringLiteral("User Prompt Template"),
         QVariant(),
         QStringLiteral("Example: Summarize the following content: {{input}}"),
         QStringLiteral("Required. Supports workflow variables such as {{input}}.")},
        {QStringLiteral("llm"),
         QStringLiteral("modelName"),
         QStringLiteral("Model Name"),
         QVariant(),
         QStringLiteral("Enter model identifier"),
         QStringLiteral("Required. Use the model identifier configured by your runtime/backend.")},
        {QStringLiteral("llm"),
         QStringLiteral("temperature"),
         QStringLiteral("Temperature"),
         0.0,
         QString(),
         QStringLiteral("Lower temperatures are more deterministic; higher temperatures are more creative.")},
        {QStringLiteral("llm"),
         QStringLiteral("maxTokens"),
         QStringLiteral("Max Tokens"),
         1,
         QString(),
         QStringLiteral("Maximum number of tokens this node may generate.")},
        {QStringLiteral("tool"),
         QStringLiteral("toolName"),
         QStringLiteral("Tool Name"),
         QVariant(),
         QStringLiteral("Example: web_search"),
         QStringLiteral("Required. Must match a registered tool identifier.")},
        {QStringLiteral("tool"),
         QStringLiteral("timeoutMs"),
         QStringLiteral("Timeout (ms)"),
         QVariant(),
         QString(),
         QStringLiteral("Optional timeout in milliseconds. Use 0 to keep the runtime default.")},
        {QStringLiteral("tool"),
         QStringLiteral("inputMapping"),
         QStringLiteral("Input Mapping"),
         QVariant(),
         QStringLiteral("Example: {\"query\": \"{{input}}\"}"),
         QStringLiteral("Optional. Provide a JSON object that maps workflow values into tool inputs.")},
    };
}
